### ISSUE TITLE
Questions: Rationals behind superlogin-client

### ISSUE THREAD

**Issue by cgestes** [micky2be/superlogin-client#75]
Hi,

thank you for this great project. I have some questions I would like to figure out, I hope you can help me.

1/ Why do we need an interceptor? Cant we just provide an Authorization Bearers to our request and let the client implement an interceptor if he wants. We could provide a way to do that without having it integrated by default.

2/ Why is superlogin-client a singleton and not a class we can instanciate multiple times?
I guess the interceptor is part of the answer...
It makes it harder to have isolated test.

3/ Would you mind accepting patch to support async storage?
(I had to implement an async storage on top of pouchdb to support node)
So I had to modify the code everywhere to support async storage.
I also added a way to provide a custom storage class to superlogin-client.

**Comment by micky2be** [comment]
1/ Superlogin will refresh the token when needed. The idea is to have the bearer updated automatically.

2/ Well, do you see a need to be authenticated multiple times to different Superlogin servers? 
That's why it's a singleton. But we could add an option if necessary.
The interceptor exist only on a dedicates instance of Axios. It was made this way so if you use Axios yourself the interceptor will not trigger.

3/ superlogin-client is supposed to be browser base. If you see a need for node, why not.
If the fundamentals of the client is not changed, I'll be happy to check your PR.
